### PR TITLE
Fix issue 1

### LINKED ISSUE #1: Python 3.11: mutable default PhoneNumber for field source is not allowed
On CPython 3.11, I am running into:

```
(cpy3113_1) oberstet@thinkpad-t430s:~$ python -V
Python 3.11.3
(cpy3113_1) oberstet@thinkpad-t430s:~$ pip show aiosmpplib
Name: aiosmpplib
Version: 0.6.3
Summary: Python asyncio SMPP client library.
Home-page: https://github.com/niksabaldun/aiosmpplib
Author: Nikša Baldun
Author-email: niksa.baldun@gmail.com
License: MIT
Location: /home/oberstet/cpy3113_1/lib/python3.11/site-packages
Requires: 
Required-by: jasmin-nga
(cpy3113_1) oberstet@thinkpad-t430s:~$ python -c "from aiosmpplib import PhoneNumber"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/__init__.py", line 2, in <module>
    from .esme import ESME
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/esme.py", line 8, in <module>
    from .broker import AbstractBroker, SimpleBroker
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/broker.py", line 5, in <module>
    from .protocol import SmppMessage
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/protocol.py", line 131, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'aiosmpplib.state.PhoneNumber'> for field source is not allowed: use default_factory
(cpy3113_1) oberstet@thinkpad-t430s:~$ 
```

https://github.com/niksabaldun/aiosmpplib/blob/b142b784a47df822f7290352c0381b0dfb9d559f/aiosmpplib/protocol.py#L131

----------

This does not happen on older Python, e.g. here is the same test on PyPy:

```
(pypy39_1) oberstet@thinkpad-t430s:~$ python -V
Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 14:23:21)
[PyPy 7.3.11 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
(pypy39_1) oberstet@thinkpad-t430s:~$ pip show aiosmpplib
Name: aiosmpplib
Version: 0.6.3
Summary: Python asyncio SMPP client library.
Home-page: https://github.com/niksabaldun/aiosmpplib
Author: Nikša Baldun
Author-email: niksa.baldun@gmail.com
License: MIT
Location: /home/oberstet/pypy39_1/lib/pypy3.9/site-packages
Requires: 
Required-by: jasmin-nga
(pypy39_1) oberstet@thinkpad-t430s:~$ python -c "from aiosmpplib import PhoneNumber"
(pypy39_1) oberstet@thinkpad-t430s:~$ 
```

### PR DESCRIPTION
**Pull request by oberstetpanamax**
this fixes #1, and also adds tox testing and fixes flake8 issues ...

### CODE REVIEW

**Comment by oberstetpanamax** [comment]
local testing works:

```
(cpy3113_1) oberstet@thinkpad-t430s:~/scm/panamax/aiosmpplib$ tox
.pkg: _optional_hooks> python /home/oberstet/cpy3113_1/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/oberstet/cpy3113_1/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /home/oberstet/cpy3113_1/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /home/oberstet/cpy3113_1/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
flake8: install_package> python -I -m pip install --force-reinstall --no-deps /home/oberstet/scm/panamax/aiosmpplib/.tox/.tmp/package/34/aiosmpplib-0.6.3.tar.gz
flake8: commands[0]> flake8 -v --statistics --max-line-length=119 /home/oberstet/scm/panamax/aiosmpplib/aiosmpplib/ '--exclude=/home/oberstet/scm/panamax/aiosmpplib/tests/*'
flake8.checker            MainProcess    123 INFO     Making checkers
flake8.main.application   MainProcess    568 INFO     Finished running
flake8.main.application   MainProcess    568 INFO     Reporting errors
flake8.main.application   MainProcess    569 INFO     Found a total of 12 violations and reported 0
flake8: OK ✔ in 2.58 seconds
pyimports: install_package> python -I -m pip install --force-reinstall --no-deps /home/oberstet/scm/panamax/aiosmpplib/.tox/.tmp/package/35/aiosmpplib-0.6.3.tar.gz
pyimports: commands[0]> python -c 'from aiosmpplib import PhoneNumber'
pyimports: OK ✔ in 1.68 seconds
py39: skipped because could not find python interpreter with spec(s): py39
py39: SKIP ⚠ in 0.01 seconds
py311: install_package> python -I -m pip install --force-reinstall --no-deps /home/oberstet/scm/panamax/aiosmpplib/.tox/.tmp/package/36/aiosmpplib-0.6.3.tar.gz
py311: commands[0]> pip install -U pip
Requirement already satisfied: pip in ./.tox/py311/lib/python3.11/site-packages (23.1.2)
py311: commands[1]> pytest --basetemp=/home/oberstet/scm/panamax/aiosmpplib/.tox/py311/tmp
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
cachedir: .tox/py311/.pytest_cache
rootdir: /home/oberstet/scm/panamax/aiosmpplib
collected 128 items                                                                                                                                                    

tests/test_codecs.py .............................                                                                                                               [ 22%]
tests/test_protocol.py ...................................................................................................                                       [100%]

========================================================================= 128 passed in 0.28s ==========================================================================
py311: OK ✔ in 3.47 seconds
pypy39: skipped because could not find python interpreter with spec(s): pypy39
.pkg: _exit> python /home/oberstet/cpy3113_1/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  flake8: OK (2.58=setup[1.94]+cmd[0.64] seconds)
  pyimports: OK (1.68=setup[1.53]+cmd[0.15] seconds)
  py39: SKIP (0.01 seconds)
  py311: OK (3.47=setup[1.53]+cmd[1.31,0.64] seconds)
  pypy39: SKIP (0.05 seconds)
  congratulations :) (7.88 seconds)
(cpy3113_1) oberstet@thinkpad-t430s:~/scm/panamax/aiosmpplib$ 
```

**Comment by niksabaldun** [comment]
OK, so as far as I can see, the only actual code change is in SubmitSm class?

**Comment by oberstetpanamax** [comment]
@niksabaldun yes. the actual fix is the 1st commit, that is https://github.com/niksabaldun/aiosmpplib/pull/2/commits/0f94027887c532657f8502961c201a299c736ecb

the other commits are just whitespace and test infra ..

**Comment by oberstetpanamax** [comment]
mypy is also still complaining about some things that IMO would be worth looking at / fixing .. but I didn't do that now

```
(cpy3113_1) oberstet@thinkpad-t430s:~/scm/panamax/aiosmpplib$ mypy --config-file mypy.ini aiosmpplib
aiosmpplib/utils.py:15: error: Argument 2 to "isinstance" has incompatible type "<typing special form>"; expected "_ClassInfo"  [arg-type]
aiosmpplib/utils.py:16: error: Item "Tuple[Type[Any], ...]" of "Union[Type[Any], Tuple[Type[Any]]]" has no attribute "__name__"  [union-attr]
aiosmpplib/utils.py:18: error: Name "type_names" already defined on line 16  [no-redef]
aiosmpplib/utils.py:33: error: Attribute "offset" already defined on line 31  [no-redef]
aiosmpplib/utils.py:68: error: Name "time_delta" already defined on line 66  [no-redef]
aiosmpplib/state.py:466: error: Missing return statement  [return]
aiosmpplib/protocol.py:192: error: Argument 3 to "check_param" has incompatible type "Tuple[Type[datetime], Type[timedelta]]"; expected "Union[Type[Any], Tuple[Type[Any]]]"  [arg-type]
aiosmpplib/protocol.py:193: error: Argument 3 to "check_param" has incompatible type "Tuple[Type[datetime], Type[timedelta]]"; expected "Union[Type[Any], Tuple[Type[Any]]]"  [arg-type]
aiosmpplib/protocol.py:247: error: Name "offset_str" already defined on line 240  [no-redef]
aiosmpplib/protocol.py:248: error: Name "prefix" already defined on line 241  [no-redef]
aiosmpplib/protocol.py:329: error: Name "codec_info" already defined on line 326  [no-redef]
aiosmpplib/protocol.py:330: error: Name "result" already defined on line 327  [no-redef]
aiosmpplib/protocol.py:333: error: Name "codec_info" already defined on line 326  [no-redef]
aiosmpplib/protocol.py:334: error: Name "result" already defined on line 327  [no-redef]
aiosmpplib/protocol.py:345: error: Name "data_coding" already defined on line 343  [no-redef]
aiosmpplib/protocol.py:380: error: No binding for nonlocal "index" found  [misc]
aiosmpplib/protocol.py:387: error: No binding for nonlocal "index" found  [misc]
aiosmpplib/protocol.py:395: error: No binding for nonlocal "index" found  [misc]
aiosmpplib/protocol.py:424: error: Name "encoding" already defined on line 422  [no-redef]
aiosmpplib/protocol.py:496: error: Name "optional_params" already defined on line 494  [no-redef]
aiosmpplib/protocol.py:594: error: No binding for nonlocal "index" found  [misc]
aiosmpplib/protocol.py:733: error: No binding for nonlocal "index" found  [misc]
aiosmpplib/protocol.py:740: error: No binding for nonlocal "index" found  [misc]
aiosmpplib/log.py:53: error: Argument 3 to "check_param" has incompatible type "Tuple[Type[int], Type[str]]"; expected "Union[Type[Any], Tuple[Type[Any]]]"  [arg-type]
aiosmpplib/log.py:90: error: Signature of "exception" incompatible with supertype "Logger"  [override]
aiosmpplib/log.py:90: note:      Superclass:
aiosmpplib/log.py:90: note:          def exception(self, msg: object, *args: object, exc_info: Union[None, bool, Union[Tuple[Type[BaseException], BaseException, Optional[TracebackType]], Tuple[None, None, None]], BaseException] = ..., stack_info: bool = ..., stacklevel: int = ..., extra: Optional[Mapping[str, object]] = ...) -> None
aiosmpplib/log.py:90: note:      Subclass:
aiosmpplib/log.py:90: note:          def exception(self, msg: Any, *args: Any, exc_info: bool = ..., **kwargs: Any) -> Any
aiosmpplib/log.py:229: error: Incompatible types in assignment (expression has type "deque[LogRecord]", base class "BufferingHandler" defined the type as "List[LogRecord]")  [assignment]
aiosmpplib/esme.py:137: error: Argument 3 to "check_param" has incompatible type "Tuple[Type[int], Type[str]]"; expected "Union[Type[Any], Tuple[Type[Any]]]"  [arg-type]
aiosmpplib/esme.py:485: error: Argument 1 to "get" of "AbstractCorrelator" has incompatible type "Optional[SmppCommand]"; expected "SmppCommand"  [arg-type]
aiosmpplib/esme.py:625: error: Unexpected keyword argument "system_id" for "SmppMessage"  [call-arg]
aiosmpplib/esme.py:625: error: Unexpected keyword argument "password" for "SmppMessage"  [call-arg]
aiosmpplib/esme.py:625: error: Unexpected keyword argument "system_type" for "SmppMessage"  [call-arg]
aiosmpplib/esme.py:625: error: Unexpected keyword argument "interface_version" for "SmppMessage"  [call-arg]
aiosmpplib/esme.py:625: error: Unexpected keyword argument "addr_ton" for "SmppMessage"  [call-arg]
aiosmpplib/esme.py:625: error: Unexpected keyword argument "addr_npi" for "SmppMessage"  [call-arg]
aiosmpplib/esme.py:625: error: Unexpected keyword argument "address_range" for "SmppMessage"  [call-arg]
aiosmpplib/esme.py:671: error: Name "all_tasks" already defined on line 661  [no-redef]
Found 36 errors in 5 files (checked 16 source files)
(cpy3113_1) oberstet@thinkpad-t430s:~/scm/panamax/aiosmpplib$ 
```

**Comment by niksabaldun** [comment]
@oberstetpanamax I am using Pyright, and it does not complain about any of those. There is probably no problem with the code, though it may go against recommended coding practices. I didn't yet have the time to polish the library and write all the unit tests.

Anyway, the request is merged and new version published to PyPi.

**Pull request merged**
